### PR TITLE
use augmented arithmetic to ensure adequate precision for calculating…

### LINKED ISSUE #57: ray.intersect tolerance is unrealistic
**Describe the bug**
The default tolerance (tol=) of the ray.intersect is set smaller than the machine epsilon.  Leading to RayIntersection.SKEW results (sometimes incorrectly)

**To Reproduce**
test case in my fork branch and workaround:
https://github.com/cshorler/NURBS-Python/tree/relax_ray_intersect_tolerance
(need to rebase this on master if PR is required before integrating other PR - happy to do either).

**Expected Behavior**
My quick fix was to change the default tolerance to be a multiple of machine epsilon after investigating a few likely causes in linalg module.  In the long term, I think the correct thing to do would be change the implementation to improve the accuracy.

**Configuration:**
 - OS: Tested on Windows 10 (Python 2.7), Linux openSUSE (Python 3.6)
 - Python distribution:. Anaconda & OS default
 - Python version: see above
 - geomdl install source: GitHub
 - geomdl version/branch: master, and others

### PR DESCRIPTION
**Pull request by cshorler**
… ray intersections

fixes #57

### CODE REVIEW

**Comment by orbingol** [comment]
Although I am fine with using `doubledouble` (I have heard about it a couple of years ago as an alternative to built-in `float`), I would like to leave this PR to the next major release. I think geomdl can use it package-wide to increase precision in nearly all floating point operations, not only for `ray` and `linalg` modules. That's going to take some time to implement, test and release. I also don't want to break the existing code base because of an unexpected error.

As a temporary fix, I'll merge #59 and whenever I start `v6.x` development branch, I will test this PR and merge. Approximate time to start `v6.x` development branch is at the end of September 2019.

**Comment by cshorler** [comment]
sounds good, thanks!

**Comment by cshorler** [comment]
thinking a bit further on this - it's probably wise to split the "internal" interface from external, the library needs to return accurate results internally - but does the user really need doubledouble values (unless they ask for them).  I'm thinking on how to cleanly handle this and make a proposal.

**Comment by orbingol** [comment]
> thinking a bit further on this - it's probably wise to split the "internal" interface from external, the library needs to return accurate results internally - but does the user really need doubledouble values (unless they ask for them). 

Users should only need the Python standard library references, such as`float`, `int`, etc. I see that `doubledouble.DoubleDouble` provides a `__float__` method which should return a `float` instance when `float(x)` is called, where `x` is a `doubledouble.DoubleDouble` instance. Therefore, it shouldn't be a big problem to cast to float as a return value.

**Review by orbingol — APPROVED** [review]
I will be merging this PR with 6.x-dev and use `doubledouble` in all possible places and ensure that outside the library, everything is `float`.

Thank you so much for your contribution @cshorler !

**Pull request merged**
