### PR TITLE
JSON support

### PR DESCRIPTION
**Pull request by plang85**
Hi! Thanks for sharing your library, saves me tons of coding right now. I've added json input support for the Curve type if you're interested.

Cheers,
Philipp

### CODE REVIEW

**Comment by orbingol** [comment]
@plang85 thank you very much for your contribution Philipp. It would be very nice to support JSON for general compatibility and inter-operation of systems.

I would like to comment on the naming standard that I want to preserve through this project. I tried to name functions and properties with respect to their usages. For instance, you can use `knotvector_u` when you want to access the knot vector on the u-direction in the Surface object. This is very similar in reading control points. I believe that renaming `read_json` to something like `read_ctrlpts_json` would maintain easy readability in the documentation and easy access to the functions when using syntax completion in IDEs.

I also think that it would be better to move `parse_json` to `utilities.py` in order to reuse it for the Surface class. In that case, it will probably need some modification, but I think it should be easy to add a flag to function signature to choose between Surface and Curve classes.

**Comment by plang85** [comment]
you got it

**Comment by plang85** [comment]
sure. had to refactor a little, outsourced the whole thing to a new namespace. cheers

**Comment by orbingol** [comment]
@plang85 awesome :) You even included some unit tests, I still need to re-organize my unit tests which I wrote for testing the other parts of the code. Thank you very much for your hard work.

I have some small questions, just to clarify and test it on my side.

* What does `dim` variable do?
* I may be wrong but it seems you always try to generate knot vectors automatically (lines 113-120 of factories.py) using `utilities.autogen_knotvector()` function. I think It would be better to auto-generate if the user forgets to add a knot vector to the input file. What do you think about it?

**Comment by plang85** [comment]
@orbingol hi man,
(1) the dim variable is needed to read the flat arrays, ie to know how many points in u and v they contain. 
(2) you're right, the auto knot vector is always computed, and just discarded when a user provided one is available. this should be improved - I'm just a little pressed in time right now and won't be able to get back to this any time soon.
cheers,Philipp

**Comment by orbingol** [comment]
@plang85 No worries :) Take your time. I am a little bit busy on these days too.

After I test it, I can merge with a development branch and I may be able to improve some of the features on. For instance, `dim` variable seemed extra for me as it is always to get the size of the lists with `len()` function. This is some kind of loud thinking, `dim` might become a necessary variable too. On the other hand, I definitely need to update [RtD](http://nurbs-python.readthedocs.io/en/latest/) documentation :) Anyways, thank you very much again for your hard work :)

**Pull request merged**
