### PR TITLE
Fix file paths in examples

### PR DESCRIPTION
**Pull request by heczis**
I wasn't able to run some examples on linux, this should fix it.

### CODE REVIEW

**Comment by orbingol** [comment]
Thank you very much for testing under Linux @heczis :) I have another idea: Wouldn't it be better to add the below code segment at the top of the examples?

```python
import os
import sys
sys.path.append(os.getcwd())
```

It basically appends the current working directory, which the script runs at the time of execution, to the path. What do you think about it?

**Comment by heczis** [comment]
`sys.path` contains the search paths for modules to be imported (https://docs.python.org/3/library/sys.html?highlight=sys.path#sys.path).

What this pull request should fix is the path to an input file, which is read using `open` etc.
The problem being that `\` is used as path separator in Windows but `/` in unix-like OSes.
I think that appending the working directory to `sys.path` does not solve this.

**Comment by orbingol** [comment]
Then, after adding `sys.path.append` at the top, changing path separators from `\` to `/` should work fine. In some other project, I made this work under Windows and Linux by using `sys.path.append` and `/` path separator. I think this maintains better readability through the examples.

In my opinion, adding os.sep.join inside `read_ctrlpts` makes the code a little bit cryptic, as less experienced users might need to check Python documentation to understand what we are doing to read a simple data file.

Please correct me if I am wrong.

**Comment by heczis** [comment]
I agree that the more readable way is better.
I did some experiments on a Windows machine and it seems to me that it can handle both `/` and `\` as path separator without any `sys.path` manipulation. This way we would have
```python
curve.read_ctrlpts("data/CP_Curve1.txt")
```
but I am not sure if this works in general - It is completely new to me that this works under Windows :-]

We could also use a slightly less cryptic way of joining paths than I used originally:
```python
ctrlpts_file = os.path.join("data", "CP_Curve1.txt")
curve.read_ctrlpts(ctrlpts_file)
```
This has the advantage of explicitly stating that we join path components.

I'd go for the first option (i.e. just change path separator to `/`) provided it works for everyone else.

**Comment by orbingol** [comment]
@heczis it should work fine under Windows. I believe it path joining, in all cases, would confuse less experienced users.  Why don't we go for the first option, i.e. `sys.path.append` + path separator change? Would you do the changes in this PR?

**Comment by heczis** [comment]
I just uploaded the changes.

I didn't include the `sys.path.append` part since I believe it should not have any impact on the path-parsing behavior. This opinion is based on my understanding of the documentation and the tests I did today on the Windows machine. Is this true? If not (i.e. the current version does not work), just let me know and I will add the missing part ;-)

**Comment by orbingol** [comment]
I just tested it and it seems to be working without `sys.path.append`. I really don't remember why I needed to include that in my other script.

Thank you very much for your contribution @heczis. I am merging this PR.

**Pull request merged**
